spring.profiles.active=dev

# JWT\u5BC6\u94A5
jwt.rememberMe.secret=BlfWzr+1ZmfaOOldoASUs7CIUaiOchWGhdo3RBpHfGA=

# RocketMQ\u914D\u7F6E
rocketmq.name-server=127.0.0.1:9876

# \u62A5\u8B66\u4E1A\u52A1\u914D\u7F6E
rocketmq.alarm.producer.group=location-producer-group
rocketmq.alarm.consumer.group=location-consumer-group

#\u8865\u507F\u4E1A\u52A1\u914D\u7F6E
rocketmq.compensate.producer.group=compensate-producer-group
rocketmq.compensate.consumer.group=compensate-consumer-group

# \u89C6\u9891\u4E1A\u52A1\u914D\u7F6E
rocketmq.video.producer.group=video-producer-group
rocketmq.video.consumer.group=video-consumer-group

# \u901A\u7528\u914D\u7F6E
rocketmq.producer.send-message-timeout=10000
rocketmq.producer.retry-times-when-send-failed=3
rocketmq.producer.retry-times-when-send-async-failed=3
rocketmq.producer.max-message-size=4194304

# \u817E\u8BAF\u4E91\u77ED\u4FE1\u914D\u7F6E
tencent.sms.secret-id=your-secret-id
tencent.sms.secret-key=your-secret-key
tencent.sms.sdk-app-id=your-sdk-app-id
tencent.sms.sign-name=your-sign-name
tencent.sms.template-id=your-template-id
tencent.sms.region=ap-guangzhou

# \u65F6\u533A\u914D\u7F6E
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# \u9AD8\u5FB7\u5730\u56FE
amap.api.url=https://restapi.amap.com/v3
amap.api.timeout=5000
amap.api.retry=3


# WebClient \u914D\u7F6E
# \u8FDE\u63A5\u8D85\u65F6\uFF08\u6BEB\u79D2\uFF09
webclient.connect-timeout=5000

# \u54CD\u5E94\u8D85\u65F6\uFF08\u79D2\uFF09
webclient.response-timeout=10

# \u6700\u5927\u8FDE\u63A5\u6570
webclient.max-connections=50

# \u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09
webclient.pending-acquire-timeout=5000

# \u97F3\u89C6\u9891\u6587\u4EF6\u4FDD\u5B58\u4F4D\u7F6E todo \u6309\u73AF\u5883\u5206\u5F00\u8BBE\u7F6E
file.video.storage.path=E:/Warning/Warn/uploads/one-click/media/video
alarm-photo.file.storage.path=E:/Warning/Warn/uploads/one-click/media/alarm-photo

# xxl-job\u914D\u7F6E
xxl.job.admin.addresses=http://localhost:9777/xxl-job-admin
xxl.job.executor.appname=late-return-face-executor
xxl.job.executor.address=
xxl.job.executor.ip=127.0.0.1
xxl.job.executor.port=9888
xxl.job.accessToken=default_token
xxl.job.executor.logpath=E:/Warning/Warn/logs/xxl-job/job-handler
xxl.job.executor.logretentiondays=30

# ElasticSearch \u914D\u7F6E todo \u6309\u73AF\u5883\u5206\u5F00\u8BBE\u7F6E
elasticsearch.host=localhost
elasticsearch.port=9200
elasticsearch.scheme=http
elasticsearch.username=elastic
elasricsearch.password=A1C*_9KUYE

# \u7D22\u5F15\u8BBE\u7F6E
elasticsearch.index.notifications=notifications
elasticsearch.index.shards=1
elasticsearch.index.replicas=0

# \u8FDE\u63A5\u8BBE\u7F6E
elasticsearch.connect.timeout=5000
elasticsearch.socket.timeout=10000
elasticsearch.connection.request.timeout=5000




