# \u6570\u636E\u5E93\u9A71\u52A8
jdbc.driver=com.mysql.cj.jdbc.Driver
# \u6570\u636E\u5E93URL
jdbc.url=jdbc:mysql://127.0.0.1:3306/warn?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
# \u6570\u636E\u5E93\u7528\u6237\u540D
jdbc.username=root
# \u6570\u636E\u5E93\u5BC6\u7801
jdbc.password=SXNX

# \u8FDE\u63A5\u6C60\u914D\u7F6E
jdbc.initialSize=5
jdbc.maxActive=30
jdbc.minIdle=3
jdbc.maxWait=60000