#Xxl-Job\u4EFB\u52A1\u8C03\u5EA6\u53C2\u6570 todo \u4E0D\u77E5\u4E3A\u4F55\u6CA1\u6CD5\u6CE8\u5165
xxl.job.admin.addresses=http://localhost:9777/xxl-job-admin
xxl.job.executor.appname=late-return-face-executor
xxl.job.executor.address=
xxl.job.executor.ip=127.0.0.1
xxl.job.executor.port=9888
xxl.job.accessToken=default_token
xxl.job.executor.logpath=E:/Warning/Warn/logs/xxl-job/job-handler
xxl.job.executor.logretentiondays=30